export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAIL = 'GET_TOKEN_FAIL';
export const SET_TOKEN = 'SET_TOKEN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const GET_ALL_HOMMIES = 'GET_ALL_HOMMIES';
export const GET_ALL_HOMMIES_SUCCESS = 'GET_ALL_HOMMIES_SUCCESS';
export const GET_ALL_HOMMIES_FAIL = 'GET_ALL_HOMMIES_FAIL';

export const CHANGE_VALUE = "CHANGE_VALUE";

export const ADD_HOMMY = "ADD_HOMMY";
export const ADD_HOMMY_SUCCESS = "ADD_HOMMY_SUCCESS";

export const DELETE_HOMMY = "DELETE_HOMMY";
export const DELETE_HOMMY_SUCCESS = "DELETE_HOMMY_SUCCESS";

export const EDIT_HOMMY = "EDIT_HOMMY";
export const EDIT_HOMMY_SUCCESS = "EDIT_HOMMY_SUCCESS";

export const CLOSE_DAY = "CLOSE_DAY";
export const CLOSE_DAY_SUCCESS = "CLOSE_DAY_SUCCESS";

export const SAVE_VALUE = "SAVE_VALUE";
export const SAVE_VALUE_SUCCESS = "SAVE_VALUE_SUCCESS";

export const GET_DAY_AMOUNT = "GET_DAY_AMOUNT";
export const GET_DAY_AMOUNT_SUCCESS = "GET_DAY_AMOUNT_SUCCESS";

export const RESET_AMOUNT = "RESET_AMOUNT";

export const GET_AMOUNT = "GET_AMOUNT";
export const GET_AMOUNT_SUCCESS = "GET_AMOUNT_SUCCESS";

export const SET_AMOUNTS = "SET_AMOUNTS";

export const SIGNUP = "SIGNUP";

